// Editorial purpose statements, not claims about benchmark coverage or model suitability.
export const categoryPurpose: Record<string, string> = {
  models: "Choose a model for the work your users actually do: answering Arabic questions, following instructions, and handling Saudi context. An overall score is a starting point; task-level results help you judge fit.",
  "coding-agents": "Software teams need working changes, not just plausible code. This category will help assess whether an agent can navigate a repository, choose tools, and complete tasks in products that serve Arabic-speaking users.",
  image: "Arabic text and right-to-left layouts matter in invoices, forms, scans, and screenshots. These evaluations will measure visual understanding, accurate text extraction, and document structure.",
  speech: "Voice services must understand how people actually speak and respond intelligibly. Arabic dialects, names, numbers, and mixed Arabic-English speech are important use cases for transcription and voice assistants.",
  video: "Video tools need to preserve meaning across moving images, speech, and captions. Relevant uses include Arabic education, accessible media, and locally appropriate content creation.",
  inference: "A useful answer must also arrive within your time and cost budget. Endpoint measurements help teams choose how to serve a model for interactive assistants, document processing, or high-volume workloads.",
  leaderboard: "Comparable evaluations help you build a shortlist without relying on marketing claims. Inspect the task breakdown and evaluation scope before choosing a model for your own workload.",
  about: "You need to know who runs an evaluation, how it is scored, and where its limits are before relying on a ranking. Methodology and source access make those decisions inspectable.",
  "ai-trends": "Repeated, comparable measurements can show whether Arabic capability is improving and whether a model upgrade is worth testing. A new release alone does not establish progress on your tasks.",
};
export const capabilityPurpose: Record<string, string> = {
  "All tasks": "See the full performance profile before narrowing your choice. Strong results in one area can hide weaknesses in another; use individual tasks to match the model to your workload.",
  "Arabic language": "Meaning depends on wording, register, and dialect. Inspect this group when choosing tools for Arabic writing, customer conversations, or interpreting informal messages.",
  "Saudi context": "An Arabic answer can still miss the local context. Inspect these tasks for questions involving Saudi references, Gulf usage, culture, and history; they do not certify legal or government-service accuracy.",
  "Knowledge & retrieval": "Workplace assistants must find relevant information and answer from evidence. These tasks are useful when assessing document questions, knowledge search, and the risk of unsupported answers.",
  "Agents & reasoning": "An assistant that takes action must select a sensible next step and use tools correctly. Inspect this group for multi-step workflows, coding assistance, and tool-routing decisions.",
  "Safety & alignment": "Useful assistants should handle risky requests carefully while still helping with legitimate ones. Inspect individual rubrics: these historical scores alone do not establish a model’s safety or cultural suitability.",
};
export const taskPurpose: Record<string, string> = {
  arabic: "Useful for assessing Arabic language tasks before choosing a writing or question-answering assistant.",
  saudi: "Useful for checking responses to Saudi-focused questions where local references affect the answer.",
  gulf: "Gulf references and usage matter when serving users across the region.",
  culture: "Cultural references affect whether an answer makes sense to its intended audience.",
  history: "Historical questions need accurate entities, dates, and context rather than a plausible story.",
  localDialects: "Informal regional wording matters in customer messages and everyday conversations.",
  slang: "Colloquial expressions can carry meanings that a literal reading misses.",
  literature: "Literary tasks help examine sensitivity to language, interpretation, and style.",
  "music&art": "Arts questions bring cultural references and creative vocabulary into evaluation.",
  footballSport: "Sports questions exercise locally relevant names, terminology, and factual context.",
  media: "Media-related questions help assess understanding of the references people encounter in public content.",
  islamic: "Religious questions require careful interpretation and factual accuracy; this task score is not scholarly validation.",
  islamic_qa: "Religious question answering needs careful handling of sources and uncertainty; qualified review remains necessary.",
  religious: "Religious context can affect interpretation and user expectations. Read the rubric before interpreting this score.",
  rag: "Retrieval-based assistants need to use supplied evidence rather than substitute unsupported knowledge.",
  document: "Document assistants must preserve details when answering questions about source material.",
  truthfulness: "Confident but incorrect answers can mislead users; factual reliability matters alongside fluency.",
  general: "Broad questions provide a baseline for everyday assistance beyond specialized domains.",
  agentic: "Multi-step assistance needs decisions that move a task toward completion.",
  agentic_tool_use: "Selecting the right tool matters when an assistant searches, retrieves information, or takes an action.",
  reasoning: "Multi-step problems help reveal whether a model can connect information consistently.",
  puzzles: "Constrained problems can expose reasoning mistakes, though puzzle success does not establish real-world task performance.",
  coding: "Code assistance needs correctness that can be checked, not merely code that looks convincing.",
  safety: "Risky requests need careful responses without blocking legitimate help. The rubric determines what this score means.",
  alignment: "Following intended instructions and constraints matters in user-facing workflows. This score reflects its rubric, not universal agreement on values.",
};
export const plannedTrackPurpose: Record<string, string> = {
  "Repository tasks": "Check whether an agent can understand existing code and make a working change.",
  "Tool decisions": "Check whether an agent selects the appropriate tool and supplies usable arguments.",
  "Task completion": "Measure whether the requested outcome was achieved, beyond individual steps.",
  "Image generation": "Assess useful visual output, including legible Arabic text and requested layout.",
  "Visual understanding": "Assess whether a model interprets the content of a screenshot or image correctly.",
  "Arabic OCR": "Accurate extraction is a prerequisite for searching and processing scanned Arabic documents.",
  "Speech to text": "Transcription quality affects search, call summaries, and voice input.",
  "Text to speech": "Intelligible pronunciation and natural delivery matter for accessible Arabic interfaces.",
  "Dialect coverage": "Separate dialect results help reveal which users a speech system may serve poorly.",
  "Video generation": "Check whether clips follow instructions and maintain visual consistency.",
  "Video understanding": "Check whether a model follows events and meaning across time, not just one frame.",
  "Output speed": "Generation speed affects how long users wait for a complete answer.",
  "Time to first token": "The initial wait affects whether a conversation feels responsive.",
  "Cost per task": "Task cost helps teams budget for actual usage rather than token prices alone.",
  "Performance over time": "Comparable repeat measurements distinguish progress from changes in the test.",
  "Arabic capability": "Track whether improvements reach Arabic workloads, rather than assume they do.",
  "Efficiency trends": "Track whether comparable work becomes faster or less costly at a given quality level.",
};

export const taskLabel = (name:string) => ({rag:"Retrieval (RAG)",arabic:"Arabic language",saudi:"Saudi knowledge",islamic_qa:"Islamic question answering",islamic:"Islamic knowledge",religious:"Religious context",agentic:"Agent reasoning",agentic_tool_use:"Tool decisions",document:"Document understanding",localDialects:"Local dialects",footballSport:"Football & sports","music&art":"Music & art"}[name] ?? name.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").replace(/^./,s=>s.toUpperCase()));
