"use client";
import {PublicationDate} from "./PublicationDate";
import {useCatalog} from "./CatalogProvider";
import {useComparison} from "./useComparison";
import {useState} from "react";
import Link from "next/link";
import type {PublicEvaluation} from "@/lib/db";

import {effortLevels,rate} from "@/lib/model-catalog";
import {ProviderLogo} from "./ProviderLogo";
import {UiIcon} from "./UiIcon";
const highlights=[{id:"arabic",name:"Arabic language",description:"Understanding and answering in Arabic",color:"#6e54b5"},{id:"saudi",name:"Saudi knowledge",description:"Knowledge grounded in Saudi context",color:"#15826d"},{id:"agentic_tool_use",name:"Tool decisions",description:"Choosing tools for the task",color:"#ce7941"}];
const labels=[['correct','Correct'],['possible_correct','Possible correct'],['partial_correct','Partial correct'],['wrong','Wrong'],['technical_failure','Technical failure']] as const;
export function AnalysisOverview({study}:{study:PublicEvaluation}) {
 const catalog=useCatalog();
 const modelNames=Object.fromEntries(catalog.map(m=>[m.id,m.displayName]));
 const modelSlug=(id:string)=>catalog.find(m=>m.id===id)?.slug??id;
 const modelColor=(id:string)=>catalog.find(m=>m.id===id)?.color??"#237757";

 const {prompt,setPrompt,level,setLevel,query}=useComparison();
 const [metric,setMetric]=useState('overall'),[detail,setDetail]=useState<string|null>(null);
 const models=Object.keys(modelNames);
 const config=(m:string)=>study.configurations.find(c=>c.model===m&&c.execution===prompt&&c.thinking===level)?.name;
 const score=(m:string,track:string)=>track==='overall'?study.configurations.find(r=>r.name===config(m)):study.configurationTracks.find(r=>r.config===config(m)&&r.name===track);
 const supplemental=(m:string)=>study.metrics.find(r=>r.config===config(m));
 const ranked=[...models].sort((a,b)=>{const x=score(a,metric),y=score(b,metric);return (y?rate(y.acceptable,y.total):-1)-(x?rate(x.acceptable,x.total):-1);});
 function download(){const csv=['model,execution,thinking,benchmark,acceptable,total,score,dataset_revision,evidence_scope',...ranked.map(m=>{const r=score(m,metric);return [modelNames[m],prompt,level,metric,r?.acceptable??'',r?.total??'',r?rate(r.acceptable,r.total).toFixed(4):'',study.datasetRevision,'historical-pre-audit'].join(',');})].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`najd-${metric}-${prompt}-${level}.csv`;a.click();URL.revokeObjectURL(url);}
 return <>
 <section id="highlights" className="analysis-highlights"><div className="section-heading"><div><h2>Performance highlights</h2><p>Acceptable answer rate · Historical results · Higher is better</p></div><div className="overview-settings"><label>Execution<select aria-label="Overview execution" value={prompt} onChange={e=>setPrompt(e.target.value)}><option value="raw">Direct (Raw)</option><option value="pi">Pi agent</option></select></label><label>Thinking<select aria-label="Overview thinking" value={level} onChange={e=>setLevel(e.target.value)}>{effortLevels.map(l=><option key={l}>{l}</option>)}</select></label></div></div>
 <div className="highlight-grid">{highlights.map(h=><article className="highlight-card" key={h.id}><div className="highlight-title"><span style={{background:h.color}}/><h3>{h.name}</h3></div><p>{h.description}</p><div className="mini-chart"><div className="chart-gridlines" aria-hidden="true">{[100,75,50,25,0].map(n=><span key={n}>{n}</span>)}</div><div className="mini-columns">{models.map(m=>{const r=score(m,h.id),value=r?rate(r.acceptable,r.total):0;const id=`${h.id}-${m}`;return <div className="mini-column" key={m}><div className="mini-bar-space"><button disabled={!r} className={`mini-bar ${m}`} style={{background:modelColor(m),height:`${value}%`}} aria-label={`${h.name}: ${modelNames[m]}, ${r?value.toFixed(2)+" percent":"not measured"}`} onMouseEnter={()=>setDetail(id)} onMouseLeave={()=>setDetail(null)} onFocus={()=>setDetail(id)} onBlur={()=>setDetail(null)} onClick={()=>setDetail(id)}><strong>{r?value.toFixed(1):'—'}</strong></button></div><Link href={{pathname:`/models/${modelSlug(m)}`,query}}><ProviderLogo model={m} size={32}/><span>{modelNames[m]}</span></Link>{detail===id&&r&&<div className="mini-tooltip" role="status">{r.acceptable} / {r.total} acceptable · {prompt.toUpperCase()} · {level}</div>}</div>;})}</div></div><button className="highlight-explore" onClick={()=>{setMetric(h.id);document.getElementById('rankings')?.scrollIntoView({behavior:'smooth',block:'start'});}}>Explore results<UiIcon name="arrow"/></button></article>)}</div>
 </section>
 <div className="analysis-services"><Link href={{pathname:'/recommender',query}}><UiIcon name="grid"/><div><strong>Find the right model</strong><span>Start with your use case</span></div><UiIcon name="arrow"/></Link><a href="mailto:salam@najdresearch.com?subject=Custom%20benchmark"><UiIcon name="chart"/><div><strong>Build your benchmark</strong><span>Evaluate what matters to your team</span></div><UiIcon name="arrow"/></a><Link href={{pathname:'/changelog'}}><UiIcon name="plus"/><div><strong>Latest updates</strong><span>Follow new results and platform changes</span></div><UiIcon name="arrow"/></Link></div>
 <nav className="analysis-jumps" aria-label="Analysis sections"><a href="#rankings">Model comparison</a><a href="#answer-quality">Answer quality</a><Link href={{pathname:"/inference",query}}>Inference</Link><a href="#thinking">Thinking levels</a></nav>
 <section id="rankings" className="analysis-section"><div className="section-heading"><div><h2>Model comparison</h2><p>One execution path and thinking setting at a time.</p></div><button className="action-button" onClick={download}><UiIcon name="download"/>Export CSV</button></div><div className="overview-settings ranking-settings"><label>Benchmark<select aria-label="Ranking benchmark" value={metric} onChange={e=>setMetric(e.target.value)}><option value="overall">Overall</option>{highlights.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}<option value="rag">Retrieval</option><option value="document">Document understanding</option><option value="safety">Safety</option></select></label><span>{prompt==='raw'?'Direct (Raw)':'Pi agent'} · {level} thinking · <a href="#highlights">Change settings</a></span></div><div className="table-scroll"><table className="analysis-table"><thead><tr><th>Model</th><th>Acceptable answer rate</th><th>Acceptable / total</th><th>Technical failures</th><th/></tr></thead><tbody>{ranked.map(m=>{const r=score(m,metric);return <tr key={m}><td><Link href={{pathname:`/models/${modelSlug(m)}`,query}}><ProviderLogo model={m} size={36}/><div><strong>{modelNames[m]}</strong><small>{catalog.find(item=>item.id===m)?.providerName}</small><small><PublicationDate value={study.configurations.find(c=>c.name===config(m))?.publishedAt}/></small></div></Link></td><td><div className="table-score"><strong>{r?rate(r.acceptable,r.total).toFixed(2):'—'}<small>%</small></strong><span><i className={m} style={{background:modelColor(m),width:`${r?rate(r.acceptable,r.total):0}%`}}/></span></div></td><td>{r?`${r.acceptable.toLocaleString()} / ${r.total.toLocaleString()}`:'—'}</td><td>{r?.technical??'—'}</td><td><Link href={{pathname:`/models/${modelSlug(m)}`,query}} aria-label={`View ${modelNames[m]}`}><UiIcon name="arrow"/></Link></td></tr>;})}</tbody></table></div><p className="analysis-note">Correct + possible correct, divided by all outputs. Technical failures contribute zero. Differences are descriptive, not a significance claim.</p></section>
 <section id="answer-quality" className="analysis-section"><div className="section-heading"><div><h2>What is behind the score?</h2><p>Answer labels across all tasks · {prompt==='raw'?'Direct (Raw)':'Pi agent'} · {level} thinking</p></div></div><div className="quality-legend">{labels.map(([key,name])=><span key={key}><i className={`grade-${key}`}/>{name}</span>)}</div><div className="quality-rows">{models.map(m=>{const r=supplemental(m);if(!r)return null;return <div className="quality-row" key={m}><Link href={{pathname:`/models/${modelSlug(m)}`,query}}><ProviderLogo model={m}/>{modelNames[m]}</Link><div className="quality-stack">{labels.map(([key,name])=>{const count=Number((r as Record<string,unknown>)[key]??0);return count>0?<button key={key} className={`grade-${key}`} style={{width:`${rate(count,r.total)}%`}} aria-label={`${modelNames[m]} ${name}: ${count}, ${rate(count,r.total).toFixed(2)} percent`} title={`${name}: ${count.toLocaleString()} (${rate(count,r.total).toFixed(2)}%)`} onClick={()=>setDetail(`${m}: ${name} — ${count.toLocaleString()} (${rate(count,r.total).toFixed(2)}%)`)}>{rate(count,r.total)>8?`${rate(count,r.total).toFixed(1)}%`:''}</button>:null;})}</div></div>;})}</div><p className="quality-detail" role="status">{detail?.includes(' — ')?detail:'Select a segment to inspect its count and share.'}</p><details className="chart-methodology"><summary>Label definitions and provenance</summary><p>Correct: normalized gold answer found. Possible correct: valid alternative. Partial correct: material omission or error. Wrong: neither a valid answer nor meaningful correct part. Technical failures remain a separate segment. Labels come from the preserved September 9 snapshot, verified against the Arena seed; they have not received a full-answer audit.</p></details></section>

 </>;
}
