"use client";
import {PublicationDate} from "./PublicationDate";
import {useCatalog} from "./CatalogProvider";
import { useComparison } from "./useComparison";
import { useState } from "react";
import { ProviderLogo } from "./ProviderLogo";
import type { PublicEvaluation } from "@/lib/db";
import { effortLevels,  rate } from "@/lib/model-catalog";
const metrics = [["overall","Overall"],["arabic","Arabic"],["saudi","Saudi"],["rag","Retrieval"],["agentic_tool_use","Tool use"],["coding","Coding"]];
function Logo({model}:{model:string}) { return <ProviderLogo model={model} size={32}/>; }
export function ReleaseExplorer({study,onlyModel,initialMetric="overall",execution}:{study:PublicEvaluation;onlyModel?:string;initialMetric?:string;execution?:"raw"|"pi"}) {
 const catalog=useCatalog();
 const modelNames=Object.fromEntries(catalog.map(m=>[m.id,m.displayName]));
 const modelSlug=(id:string)=>catalog.find(m=>m.id===id)?.slug??id;
 const modelColor=(id:string)=>catalog.find(m=>m.id===id)?.color??"#237757";

 const {prompt:selectedPrompt,setPrompt,level,setLevel}=useComparison();
 const prompt=execution??selectedPrompt;
 const [expanded,setExpanded]=useState(false);
 const [metric,setMetric]=useState(initialMetric), [format,setFormat]=useState("Chart"), [hidden,setHidden]=useState<string[]>([]), [active,setActive]=useState<string|null>(null);
 const available=Object.keys(modelNames).filter(m=>!onlyModel||m===onlyModel);
 const models=available.filter(m=>!hidden.includes(m));
 const levels=expanded?effortLevels:[level];
 const row=(m:string,level:string)=>metric==="overall"?study.configurations.find(r=>r.name===study.configurations.find(c=>c.model===m&&c.execution===prompt&&c.thinking===level)?.name):study.configurationTracks.find(r=>r.config===study.configurations.find(c=>c.model===m&&c.execution===prompt&&c.thinking===level)?.name&&r.name===metric);
 return <section className="release-explorer"><div className="explorer-heading"><div><h2>{execution==="pi"?"Coding performance with Pi":"Compare model performance"}</h2><p><span className="evidence-badge">Historical results</span> Acceptable output rate · Higher is better</p></div><div className="segmented">{["Chart","Table"].map(v=><button key={v} aria-pressed={format===v} onClick={()=>setFormat(v)}>{v}</button>)}</div></div>
 <div className="benchmark-tabs" aria-label="Benchmark">{metrics.filter(([v])=>initialMetric!=="coding"||v==="coding").map(([v,t])=><button key={v} aria-pressed={metric===v} onClick={()=>{setMetric(v);setActive(null);}}>{t}</button>)}</div>
 <div className="comparison-toolbar"><div className="provider-chips">{available.map(m=><button key={m} className={`provider-selector ${m}`} disabled={!!onlyModel} aria-label={modelNames[m]} aria-pressed={!hidden.includes(m)} onClick={()=>setHidden(hidden.includes(m)?hidden.filter(x=>x!==m):[...hidden,m])}><span className="selector-logo"><Logo model={m}/></span><span className="selector-copy"><strong>{modelNames[m]}</strong><small>{hidden.includes(m)?"Add to comparison":"In comparison"}</small></span><span className="selector-check" aria-hidden="true"><svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={hidden.includes(m)?"M8 3v10M3 8h10":"m3 8 3 3 7-7"}/></svg></span></button>)}</div><div className="comparison-filters">{execution?<span className="execution-badge">{execution==="pi"?"Pi harness":"Direct model · Raw"}</span>:<label>Execution<select aria-label="Execution path" value={prompt} onChange={e=>{setPrompt(e.target.value);setActive(null);}}><option value="raw">Direct (Raw)</option><option value="pi">Pi agent</option></select></label>}<label>Thinking level<select aria-label="Thinking level" value={level} onChange={e=>setLevel(e.target.value)}>{effortLevels.map(l=><option key={l} value={l}>{l}</option>)}</select></label></div></div>
 <button className="expand-levels" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?"Show selected setting":"Compare all thinking levels"}</button>
 {models.length===0?<div className="empty">Select a model above to compare results.</div>:format==="Chart"?<div className="level-chart">{levels.map(level=><div className="level-row" key={level}><strong>{level}</strong><div>{models.map(m=>{const r=row(m,level), id=`${m}-${level}`, score=r?rate(r.acceptable,r.total):0;return <div key={m}><div className="comparison-bar"><a href={`/models/${modelSlug(m)}?execution=${prompt}&thinking=${level}`}><Logo model={m}/>{modelNames[m]}</a><button className="comparison-track interactive-track" disabled={!r} aria-label={`${modelNames[m]}, ${level}, ${r?score.toFixed(2)+" percent":"not measured"}. Show details`} aria-expanded={active===id} onMouseEnter={()=>setActive(id)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(id)} onBlur={()=>setActive(null)} onClick={()=>setActive(id)}><i className={m} style={{background:modelColor(m),width:`${score}%`}}/></button><strong>{r?metric==="coding"?`${r.acceptable} / ${r.total}`:`${score.toFixed(2)}%`:"—"}</strong></div>{active===id&&r&&<div className="bar-details" role="status"><strong>{modelNames[m]} · {score.toFixed(2)}%</strong><span>{r.acceptable.toLocaleString()} / {r.total.toLocaleString()} acceptable</span><span>{r.technical.toLocaleString()} technical failures</span><span>{prompt==="raw"?"Direct (Raw)":"Pi agent"} · {level} thinking · {metrics.find(([v])=>v===metric)?.[1]}</span></div>}</div>;})}</div></div>)}</div>:<div className="table-scroll"><table className="results-table"><thead><tr><th>Thinking level</th>{models.map(m=><th key={m}><span className="provider-table-label"><Logo model={m}/>{modelNames[m]}</span></th>)}</tr></thead><tbody>{levels.map(level=><tr key={level}><td>{level}</td>{models.map(m=>{const r=row(m,level);return <td key={m}>{r?`${rate(r.acceptable,r.total).toFixed(2)}% · ${r.total.toLocaleString()} outputs`:"Not measured"}</td>;})}</tr>)}</tbody></table></div>}
 <div className="publication-dates">{models.map(m=>{const dates=study.configurations.filter(c=>c.model===m&&c.execution===prompt&&levels.includes(c.thinking)).map(c=>c.publishedAt).filter((v):v is string=>!!v).sort();return <div key={m}>{modelNames[m]} · <PublicationDate value={dates.at(-1)}/></div>;})}</div><p className="table-footnote">Fixed 0–100% scale · Failures count as zero.</p><details className="chart-methodology"><summary>How to read this chart</summary><p>Raw is direct model execution; Pi uses the agent runtime. These paths and their prompt settings are kept separate. Levels are API settings, not verified measures of thinking effort. “Default” uses provider defaults; “disabled” requests no reasoning. Settings may behave differently across providers.</p><p>Each overall configuration covers {study.caseCount.toLocaleString()} case IDs. These historical pre-audit results include all cases. Earlier case contents differ from the current release; no significance test is available. Hover, focus, or tap a bar to inspect its counts.</p></details></section>;
}
