import {publicEvaluation} from "@/lib/db";
import Link from "next/link";
import {ProviderLogo} from "@/components/ProviderLogo";
export const metadata={title:"About Najd Arena",description:"AI evaluation grounded in Arabic language, Saudi context, and the tasks organizations need to solve."};
export default async function About(){const study=await publicEvaluation();return <main className="shell about-page">
<section className="about-hero"><div className="eyebrow">Najd Arena · By Najd Research</div><h1>AI performance.<br/><em>Measured in context.</em></h1><p>Choosing a model starts with the problems it needs to solve. Najd Arena makes Arabic and Saudi AI performance easier to compare, understand, and reproduce.</p><div className="profile-jumps"><Link className="button" href={{pathname:"/models"}}>Explore model results →</Link><a href="mailto:salam@najdresearch.com">Talk to Najd ↗</a></div></section>
<section className="about-mission profile-section"><div><div className="eyebrow">Our purpose</div><h2>Set a clearer standard<br/>for relevant AI evaluation.</h2></div><div><p>General benchmarks offer part of the picture. Arabic language, local knowledge, and business workflows deserve their own evidence.</p><p>We are building a reference for people choosing models for Arabic customer support, Saudi knowledge questions, document assistants, and tool-using agents.</p></div></section>
<section className="profile-section"><div className="section-heading"><div><div className="eyebrow">Evaluation coverage</div><h2>What we measure</h2></div><Link href="/methodology">Read the methodology →</Link></div><div className="about-measures">{[
["01","Language & local context","Arabic understanding, Saudi knowledge, and culturally relevant questions.","/models","Available results"],
["02","Documents & retrieval","Answering questions from supplied information, with task-level breakdowns.","/models","Available text results"],
["03","Coding with a harness","Models inside Pi on the available coding tasks, keeping execution separate from direct model calls.","/coding-agents","Limited task coverage"],
["04","Enterprise vision","Visual understanding, Arabic OCR, document extraction, charts, and tables.","/image","In development"]
].map(([n,title,description,url,status])=><Link className="about-measure" href={{pathname:url}} key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p><small>{status} ↗</small></Link>)}</div></section>
<section className="profile-section"><h2>Evidence you can inspect</h2><div className="principle-grid">{[["Comparable settings","Direct model calls and agent-harness runs stay separate. Thinking settings remain visible."],["Transparent scoring","Inspect task scores, counts, and failure handling. A small score difference is not a claim of statistical significance."],["Reproducible foundations","Dataset versions and evaluation methods provide the context needed to interpret each result."]].map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div><p className="about-disclosure">The currently imported results come from a preserved historical evaluation. They are not certified runs on the exact current dataset. Each result retains its scope and limitations.</p></section>
<section className="profile-section"><h2>Models in the current results</h2><div className="about-providers">{study?.catalog.map(m=><Link key={m.id} href={{pathname:`/models/${m.slug}`}}><ProviderLogo model={m.id} size={48}/><span><strong>{m.displayName}</strong><small>View model results →</small></span></Link>)}</div><p className="table-footnote">Provider logos identify evaluated models; they do not imply partnership or endorsement.</p></section>
<section className="about-mission profile-section"><div><div className="eyebrow">Founder-led research</div><h2>Mazen Alotaibi</h2><p>Founder, Najd Research.</p></div><div><p>Najd Arena is part of Najd Research. Follow the research, explore the datasets, or help define evaluations that reflect the work you need AI to do.</p><a href="https://najdresearch.com">Explore Najd Research ↗</a></div></section>
<section className="about-contact"><div><div className="eyebrow">Build with us</div><h2>Bring a model.<br/>Bring a hard problem.</h2><p>Discuss a benchmark, contribute to the work, or report a result that needs correction.</p></div><div><a className="button" href="mailto:salam@najdresearch.com">salam@najdresearch.com ↗</a><div className="profile-jumps"><a href="https://github.com/najdresearch">GitHub ↗</a><a href="https://huggingface.co/najdresearch">Hugging Face ↗</a><a href="https://x.com/najdresearch">X ↗</a></div></div></section>
</main>}
